from chia_puzzles_py.programs import (
    NFT_INTERMEDIATE_LAUNCHER,
    NFT_METADATA_UPDATER_DEFAULT,
    NFT_OWNERSHIP_TRANSFER_PROGRAM_ONE_WAY_CLAIM_WITH_ROYALTIES,
    NFT_STATE_LAYER,
)
from chia_puzzles_py.programs import (
    NFT_OWNERSHIP_LAYER as NFT_OWNERSHIP_LAYER_BYTES,
)

from chia.types.blockchain_format.program import Program

NFT_STATE_LAYER_MOD = Program.from_bytes(NFT_STATE_LAYER)
NFT_STATE_LAYER_MOD_HASH = NFT_STATE_LAYER_MOD.get_tree_hash()
NFT_METADATA_UPDATER = Program.from_bytes(NFT_METADATA_UPDATER_DEFAULT)
NFT_METADATA_UPDATER_HASH = NFT_METADATA_UPDATER.get_tree_hash()
NFT_OWNERSHIP_LAYER = Program.from_bytes(NFT_OWNERSHIP_LAYER_BYTES)
NFT_OWNERSHIP_LAYER_HASH = NFT_OWNERSHIP_LAYER.get_tree_hash()
NFT_TRANSFER_PROGRAM_DEFAULT = Program.from_bytes(NFT_OWNERSHIP_TRANSFER_PROGRAM_ONE_WAY_CLAIM_WITH_ROYALTIES)
INTERMEDIATE_LAUNCHER_MOD = Program.from_bytes(NFT_INTERMEDIATE_LAUNCHER)