from __future__ import annotations

from chia.data_layer.data_layer import DataLayer
from chia.data_layer.data_layer_api import DataLayerAPI
from chia.farmer.farmer import Farmer
from chia.farmer.farmer_api import FarmerAPI
from chia.full_node.full_node import FullNode
from chia.full_node.full_node_api import FullNodeAPI
from chia.harvester.harvester import Harvester
from chia.harvester.harvester_api import HarvesterAPI
from chia.introducer.introducer import Introducer
from chia.introducer.introducer_api import IntroducerAPI
from chia.seeder.crawler import Crawler
from chia.seeder.crawler_api import CrawlerAPI
from chia.server.start_service import Service
from chia.simulator.full_node_simulator import FullNodeSimulator
from chia.timelord.timelord import Timelord
from chia.timelord.timelord_api import TimelordAPI
from chia.wallet.wallet_node import WalletNode
from chia.wallet.wallet_node_api import WalletNodeAPI

CrawlerService = Service[Crawler, CrawlerAPI]
DataLayerService = Service[DataLayer, DataLayerAPI]
FarmerService = Service[Farmer, FarmerAPI]
FullNodeService = Service[FullNode, FullNodeAPI]
HarvesterService = Service[Harvester, HarvesterAPI]
IntroducerService = Service[Introducer, IntroducerAPI]
SimulatorFullNodeService = Service[FullNode, FullNodeSimulator]
TimelordService = Service[Timelord, TimelordAPI]
WalletService = Service[WalletNode, WalletNodeAPI]
