from __future__ import annotations

from chia.protocols.outbound_message import NodeType
from chia.protocols.protocol_message_types import ProtocolMessageTypes

# Map of protocol message type to the node types that send it. We use this to
# validate which nodes are allowed to send which messages so that all api calls
# are type checked.
ProtocolMessageTypeToNodeType: dict[ProtocolMessageTypes, set[NodeType]] = {
    # Shared protocol (all services)
    ProtocolMessageTypes.handshake: set(NodeType),
    # Harvester protocol (harvester <-> farmer)
    ProtocolMessageTypes.harvester_handshake: {NodeType.FARMER},
    ProtocolMessageTypes.new_proof_of_space: {NodeType.HARVESTER},
    ProtocolMessageTypes.request_signatures: {NodeType.FARMER},
    ProtocolMessageTypes.respond_signatures: {NodeType.HARVESTER},
    ProtocolMessageTypes.partial_proofs: {NodeType.HARVESTER},
    ProtocolMessageTypes.new_signage_point_harvester: {NodeType.FARMER},
    ProtocolMessageTypes.request_plots: {NodeType.FARMER},
    ProtocolMessageTypes.respond_plots: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_start: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_loaded: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_removed: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_invalid: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_keys_missing: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_duplicates: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_done: {NodeType.HARVESTER},
    ProtocolMessageTypes.plot_sync_response: {NodeType.FARMER},
    # Farmer protocol (farmer <-> full_node)
    ProtocolMessageTypes.new_signage_point: {NodeType.FULL_NODE},
    ProtocolMessageTypes.declare_proof_of_space: {NodeType.FARMER},
    ProtocolMessageTypes.request_signed_values: {NodeType.FULL_NODE},
    ProtocolMessageTypes.signed_values: {NodeType.FARMER},
    ProtocolMessageTypes.farming_info: {NodeType.HARVESTER},
    ProtocolMessageTypes.solution_response: {NodeType.SOLVER},
    # Timelord protocol (timelord <-> full_node)
    ProtocolMessageTypes.new_peak_timelord: {NodeType.FULL_NODE},
    ProtocolMessageTypes.new_unfinished_block_timelord: {NodeType.FULL_NODE},
    ProtocolMessageTypes.new_infusion_point_vdf: {NodeType.TIMELORD},
    ProtocolMessageTypes.new_signage_point_vdf: {NodeType.TIMELORD},
    ProtocolMessageTypes.new_end_of_sub_slot_vdf: {NodeType.TIMELORD},
    ProtocolMessageTypes.request_compact_proof_of_time: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_compact_proof_of_time: {NodeType.TIMELORD},
    # Full node protocol (full_node <-> full_node)
    ProtocolMessageTypes.new_peak: {NodeType.FULL_NODE},
    ProtocolMessageTypes.new_transaction: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_transaction: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_transaction: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_proof_of_weight: {NodeType.WALLET, NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_proof_of_weight: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_block: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_block: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_block: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_blocks: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_blocks: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_blocks: {NodeType.FULL_NODE},
    ProtocolMessageTypes.new_unfinished_block: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_unfinished_block: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_unfinished_block: {NodeType.FULL_NODE},
    ProtocolMessageTypes.new_signage_point_or_end_of_sub_slot: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_signage_point_or_end_of_sub_slot: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_signage_point: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_end_of_sub_slot: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_mempool_transactions: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_compact_vdf: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_compact_vdf: {NodeType.FULL_NODE},
    ProtocolMessageTypes.new_compact_vdf: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_peers: {NodeType.WALLET, NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_peers: {NodeType.FULL_NODE},
    # No one currently sends none responses as it's gated by a capability
    # that is currently disabled. Revisit when the none response capability
    # gets enabled.
    ProtocolMessageTypes.none_response: set(),
    ProtocolMessageTypes.new_unfinished_block2: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_unfinished_block2: {NodeType.FULL_NODE},
    # Wallet protocol (wallet <-> full_node)
    ProtocolMessageTypes.request_puzzle_solution: {NodeType.WALLET},
    ProtocolMessageTypes.respond_puzzle_solution: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_puzzle_solution: {NodeType.FULL_NODE},
    ProtocolMessageTypes.send_transaction: {NodeType.WALLET},
    ProtocolMessageTypes.transaction_ack: {NodeType.FULL_NODE},
    ProtocolMessageTypes.new_peak_wallet: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_block_header: {NodeType.WALLET},
    ProtocolMessageTypes.respond_block_header: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_header_request: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_removals: {NodeType.WALLET},
    ProtocolMessageTypes.respond_removals: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_removals_request: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_additions: {NodeType.WALLET},
    ProtocolMessageTypes.respond_additions: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_additions_request: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_header_blocks: {NodeType.WALLET},
    ProtocolMessageTypes.reject_header_blocks: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_header_blocks: {NodeType.FULL_NODE},
    ProtocolMessageTypes.coin_state_update: {NodeType.FULL_NODE},
    ProtocolMessageTypes.register_for_ph_updates: {NodeType.WALLET},
    ProtocolMessageTypes.respond_to_ph_updates: {NodeType.FULL_NODE},
    ProtocolMessageTypes.register_for_coin_updates: {NodeType.WALLET},
    ProtocolMessageTypes.respond_to_coin_updates: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_children: {NodeType.WALLET},
    ProtocolMessageTypes.respond_children: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_ses_hashes: {NodeType.WALLET},
    ProtocolMessageTypes.respond_ses_hashes: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_block_headers: {NodeType.WALLET},
    ProtocolMessageTypes.reject_block_headers: {NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_block_headers: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_fee_estimates: {NodeType.WALLET},
    ProtocolMessageTypes.respond_fee_estimates: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_remove_puzzle_subscriptions: {NodeType.WALLET},
    ProtocolMessageTypes.respond_remove_puzzle_subscriptions: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_remove_coin_subscriptions: {NodeType.WALLET},
    ProtocolMessageTypes.respond_remove_coin_subscriptions: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_puzzle_state: {NodeType.WALLET},
    ProtocolMessageTypes.respond_puzzle_state: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_puzzle_state: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_coin_state: {NodeType.WALLET},
    ProtocolMessageTypes.respond_coin_state: {NodeType.FULL_NODE},
    ProtocolMessageTypes.reject_coin_state: {NodeType.FULL_NODE},
    ProtocolMessageTypes.mempool_items_added: {NodeType.FULL_NODE},
    ProtocolMessageTypes.mempool_items_removed: {NodeType.FULL_NODE},
    ProtocolMessageTypes.request_cost_info: {NodeType.WALLET},
    ProtocolMessageTypes.respond_cost_info: {NodeType.FULL_NODE},
    # Introducer protocol (introducer <-> full_node)
    ProtocolMessageTypes.request_peers_introducer: {NodeType.WALLET, NodeType.FARMER, NodeType.FULL_NODE},
    ProtocolMessageTypes.respond_peers_introducer: {NodeType.INTRODUCER},
    # Simulator protocol
    # TODO: We should remove this protocol message as `farm_new_block` is only
    # used via RPC nowadays. Full nodes used to send this message but not anymore.
    ProtocolMessageTypes.farm_new_block: {NodeType.FULL_NODE},
    # Solver protocol
    ProtocolMessageTypes.solve: {NodeType.FARMER},
    # Error response (handled before lookup; allow all for completeness)
    ProtocolMessageTypes.error: set(NodeType),
}
