# .github/release.yml

changelog:
  exclude:
    labels:
      - CI
      - Tests
      - Cleanup
      - dependencies
    authors:
      - octocat
      - dependabot
      - snyk-bot
      - github-actions
  categories:
    - title: Added
      labels:
        - Added
    - title: Modified
      labels:
        - Modified
    - title: Fixed
      labels:
        - Fixed
