overrides:
  - files: ["*.yaml", "*.yml", "*.toml", "*.json", "*.ini"]
    options:
      tabWidth: 2
      singleQuote: false
      experimentalTernaries: true
      useTabs: false
  - files: ["*.md"]
    options:
      singleQuote: false
  - files: ["*.js", "*.jsx", "*.ts", "*.tsx", "*.cjs", "*.mjs"]
    options:
      printWidth: 120
      singleQuote: true
