var_overrides:
  DEPENDABOT_ACTIONS_REVIEWERS: '["cmmarslender", "altendky"]'
  DEPENDENCY_REVIEW_ALLOW_DEPENDENCIES_LICENSES: pkg:pypi/pyinstaller, pkg:pypi/mypy
  DEPENDABOT_PIP_PULL_REQUEST_LIMIT: "30"
