var_overrides:
  DEPENDABOT_ACTIONS_REVIEWERS: '["cameroncooper"]'
  DEPENDENCY_REVIEW_ALLOW_DEPENDENCIES_LICENSES: pkg:pypi/pyinstaller, pkg:pypi/mypy
  DEPENDABOT_PIP_PULL_REQUEST_LIMIT: "30"
  DEPENDABOT_PIP_CHIA_REGISTRY: "1"
