var_overrides:
  DEPENDABOT_ACTIONS_REVIEWERS: '["cmmarslender", "altendky"]'
  DEPENDABOT_PIP_REBASE_STRATEGY: disabled
  DEPENDENCY_REVIEW_ALLOW_DEPENDENCIES_LICENSES: pkg:pypi/pyinstaller, pkg:pypi/mypy
