enum WalletType {
  STANDARD_WALLET = 'STANDARD_WALLET',
  RATE_LIMITED = 'RATE_LIMITED',
  ATOMIC_SWAP = 'ATOMIC_SWAP',
  AUTHORIZED_PAYEE = 'AUTHORIZED_PAYEE',
  MULTI_SIG = 'MULTI_SIG',
  CUSTODY = 'CUSTODY',
  COLOURED_COIN = 'COLOURED_COIN',
  RECOVERABLE = 'RECOVERABLE',
}

export default WalletType;
