from __future__ import annotations

from dataclasses import dataclass

from chia.data_layer.data_layer_util import DLProof, VerifyProofResponse
from chia.util.streamable import Streamable
from chia.wallet import wallet_request_types
from chia.wallet.puzzles.clawback.metadata import AutoClaimSettings


@dataclass(frozen=True, kw_only=True)
class RpcMetadata:
    endpoint_name: str
    request_type: type[Streamable]
    response_type: type[Streamable]


@dataclass(frozen=True, kw_only=True)
class WalletRpcMetadata(RpcMetadata):
    tx_endpoint: bool = False
    auto_push: bool = False
    auto_merge_spends: bool = True

    def __post_init__(self) -> None:
        if self.tx_endpoint and not issubclass(self.request_type, wallet_request_types.TransactionEndpointRequest):
            raise ValueError("tx_endpoint request type must subclass TransactionEndpointRequest")
        if self.tx_endpoint and not issubclass(self.response_type, wallet_request_types.TransactionEndpointResponse):
            raise ValueError("tx_endpoint response type must subclass TransactionEndpointResponse")


WALLET_RPC_ENDPOINT_METADATA: list[WalletRpcMetadata] = [
    # Key management
    WalletRpcMetadata(
        endpoint_name="log_in",
        request_type=wallet_request_types.LogIn,
        response_type=wallet_request_types.LogInResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_logged_in_fingerprint",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetLoggedInFingerprintResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_public_keys",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetPublicKeysResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_private_key",
        request_type=wallet_request_types.GetPrivateKey,
        response_type=wallet_request_types.GetPrivateKeyResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="generate_mnemonic",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GenerateMnemonicResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="add_key",
        request_type=wallet_request_types.AddKey,
        response_type=wallet_request_types.AddKeyResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="delete_key",
        request_type=wallet_request_types.DeleteKey,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="check_delete_key",
        request_type=wallet_request_types.CheckDeleteKey,
        response_type=wallet_request_types.CheckDeleteKeyResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="delete_all_keys",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.Empty,
    ),
    # Wallet node
    WalletRpcMetadata(
        endpoint_name="set_wallet_resync_on_startup",
        request_type=wallet_request_types.SetWalletResyncOnStartup,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="get_sync_status",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetSyncStatusResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_full_node_peer_count",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetFullNodePeerCountResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_height_info",
        request_type=wallet_request_types.GetHeightInfo,
        response_type=wallet_request_types.GetHeightInfoResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="push_tx",
        request_type=wallet_request_types.PushTX,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="push_transactions",
        request_type=wallet_request_types.PushTransactions,
        response_type=wallet_request_types.PushTransactionsResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="get_timestamp_for_height",
        request_type=wallet_request_types.GetTimestampForHeight,
        response_type=wallet_request_types.GetTimestampForHeightResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_fee_estimate",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetFeeEstimateResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="set_auto_claim",
        request_type=AutoClaimSettings,
        response_type=AutoClaimSettings,
    ),
    WalletRpcMetadata(
        endpoint_name="get_auto_claim",
        request_type=wallet_request_types.Empty,
        response_type=AutoClaimSettings,
    ),
    # Wallet management
    WalletRpcMetadata(
        endpoint_name="get_wallets",
        request_type=wallet_request_types.GetWallets,
        response_type=wallet_request_types.GetWalletsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="create_new_wallet",
        request_type=wallet_request_types.CreateNewWallet,
        response_type=wallet_request_types.CreateNewWalletResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    # Wallet
    WalletRpcMetadata(
        endpoint_name="get_wallet_balance",
        request_type=wallet_request_types.GetWalletBalance,
        response_type=wallet_request_types.GetWalletBalanceResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_wallet_balances",
        request_type=wallet_request_types.GetWalletBalances,
        response_type=wallet_request_types.GetWalletBalancesResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_transaction",
        request_type=wallet_request_types.GetTransaction,
        response_type=wallet_request_types.GetTransactionResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_transactions",
        request_type=wallet_request_types.GetTransactions,
        response_type=wallet_request_types.GetTransactionsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_transaction_count",
        request_type=wallet_request_types.GetTransactionCount,
        response_type=wallet_request_types.GetTransactionCountResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_next_address",
        request_type=wallet_request_types.GetNextAddress,
        response_type=wallet_request_types.GetNextAddressResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="send_transaction",
        request_type=wallet_request_types.SendTransaction,
        response_type=wallet_request_types.SendTransactionResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="send_transaction_multi",
        request_type=wallet_request_types.SendTransactionMulti,
        response_type=wallet_request_types.SendTransactionMultiResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="spend_clawback_coins",
        request_type=wallet_request_types.SpendClawbackCoins,
        response_type=wallet_request_types.SpendClawbackCoinsResponse,
        tx_endpoint=True,
        auto_push=True,
        auto_merge_spends=False,
    ),
    # get_coin_records remains a legacy untyped endpoint.
    WalletRpcMetadata(
        endpoint_name="get_farmed_amount",
        request_type=wallet_request_types.GetFarmedAmount,
        response_type=wallet_request_types.GetFarmedAmountResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="create_signed_transaction",
        request_type=wallet_request_types.CreateSignedTransaction,
        response_type=wallet_request_types.CreateSignedTransactionsResponse,
        tx_endpoint=True,
    ),
    WalletRpcMetadata(
        endpoint_name="delete_unconfirmed_transactions",
        request_type=wallet_request_types.DeleteUnconfirmedTransactions,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="select_coins",
        request_type=wallet_request_types.SelectCoins,
        response_type=wallet_request_types.SelectCoinsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_spendable_coins",
        request_type=wallet_request_types.GetSpendableCoins,
        response_type=wallet_request_types.GetSpendableCoinsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_coin_records_by_names",
        request_type=wallet_request_types.GetCoinRecordsByNames,
        response_type=wallet_request_types.GetCoinRecordsByNamesResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_puzzle_and_solution",
        request_type=wallet_request_types.GetPuzzleAndSolution,
        response_type=wallet_request_types.GetPuzzleAndSolutionResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_current_derivation_index",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetCurrentDerivationIndexResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="extend_derivation_index",
        request_type=wallet_request_types.ExtendDerivationIndex,
        response_type=wallet_request_types.ExtendDerivationIndexResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_notifications",
        request_type=wallet_request_types.GetNotifications,
        response_type=wallet_request_types.GetNotificationsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="delete_notifications",
        request_type=wallet_request_types.DeleteNotifications,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="send_notification",
        request_type=wallet_request_types.SendNotification,
        response_type=wallet_request_types.SendNotificationResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="sign_message_by_address",
        request_type=wallet_request_types.SignMessageByAddress,
        response_type=wallet_request_types.SignMessageByAddressResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="sign_message_by_id",
        request_type=wallet_request_types.SignMessageByID,
        response_type=wallet_request_types.SignMessageByIDResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="verify_signature",
        request_type=wallet_request_types.VerifySignature,
        response_type=wallet_request_types.VerifySignatureResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_transaction_memo",
        request_type=wallet_request_types.GetTransactionMemo,
        response_type=wallet_request_types.GetTransactionMemoResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="split_coins",
        request_type=wallet_request_types.SplitCoins,
        response_type=wallet_request_types.SplitCoinsResponse,
        tx_endpoint=True,
    ),
    WalletRpcMetadata(
        endpoint_name="combine_coins",
        request_type=wallet_request_types.CombineCoins,
        response_type=wallet_request_types.CombineCoinsResponse,
        tx_endpoint=True,
    ),
    # CATs and trading
    WalletRpcMetadata(
        endpoint_name="cat_set_name",
        request_type=wallet_request_types.CATSetName,
        response_type=wallet_request_types.CATSetNameResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="cat_asset_id_to_name",
        request_type=wallet_request_types.CATAssetIDToName,
        response_type=wallet_request_types.CATAssetIDToNameResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="cat_get_name",
        request_type=wallet_request_types.CATGetName,
        response_type=wallet_request_types.CATGetNameResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_stray_cats",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetStrayCATsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="cat_spend",
        request_type=wallet_request_types.CATSpend,
        response_type=wallet_request_types.CATSpendResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="cat_get_asset_id",
        request_type=wallet_request_types.CATGetAssetID,
        response_type=wallet_request_types.CATGetAssetIDResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="create_offer_for_ids",
        request_type=wallet_request_types.CreateOfferForIDs,
        response_type=wallet_request_types.CreateOfferForIDsResponse,
        tx_endpoint=True,
    ),
    WalletRpcMetadata(
        endpoint_name="get_offer_summary",
        request_type=wallet_request_types.GetOfferSummary,
        response_type=wallet_request_types.GetOfferSummaryResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="check_offer_validity",
        request_type=wallet_request_types.CheckOfferValidity,
        response_type=wallet_request_types.CheckOfferValidityResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="take_offer",
        request_type=wallet_request_types.TakeOffer,
        response_type=wallet_request_types.TakeOfferResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="get_offer",
        request_type=wallet_request_types.GetOffer,
        response_type=wallet_request_types.GetOfferResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_all_offers",
        request_type=wallet_request_types.GetAllOffers,
        response_type=wallet_request_types.GetAllOffersResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="get_offers_count",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetOffersCountResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="cancel_offer",
        request_type=wallet_request_types.CancelOffer,
        response_type=wallet_request_types.CancelOfferResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="cancel_offers",
        request_type=wallet_request_types.CancelOffers,
        response_type=wallet_request_types.CancelOffersResponse,
        tx_endpoint=True,
        auto_push=True,
        auto_merge_spends=False,
    ),
    WalletRpcMetadata(
        endpoint_name="get_cat_list",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.GetCATListResponse,
    ),
    # DID wallet
    WalletRpcMetadata(
        endpoint_name="did_set_wallet_name",
        request_type=wallet_request_types.DIDSetWalletName,
        response_type=wallet_request_types.DIDSetWalletNameResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_get_wallet_name",
        request_type=wallet_request_types.DIDGetWalletName,
        response_type=wallet_request_types.DIDGetWalletNameResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_update_metadata",
        request_type=wallet_request_types.DIDUpdateMetadata,
        response_type=wallet_request_types.DIDUpdateMetadataResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="did_get_pubkey",
        request_type=wallet_request_types.DIDGetPubkey,
        response_type=wallet_request_types.DIDGetPubkeyResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_get_did",
        request_type=wallet_request_types.DIDGetDID,
        response_type=wallet_request_types.DIDGetDIDResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_get_metadata",
        request_type=wallet_request_types.DIDGetMetadata,
        response_type=wallet_request_types.DIDGetMetadataResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_get_current_coin_info",
        request_type=wallet_request_types.DIDGetCurrentCoinInfo,
        response_type=wallet_request_types.DIDGetCurrentCoinInfoResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_create_backup_file",
        request_type=wallet_request_types.DIDCreateBackupFile,
        response_type=wallet_request_types.DIDCreateBackupFileResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_transfer_did",
        request_type=wallet_request_types.DIDTransferDID,
        response_type=wallet_request_types.DIDTransferDIDResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="did_message_spend",
        request_type=wallet_request_types.DIDMessageSpend,
        response_type=wallet_request_types.DIDMessageSpendResponse,
        tx_endpoint=True,
    ),
    WalletRpcMetadata(
        endpoint_name="did_get_info",
        request_type=wallet_request_types.DIDGetInfo,
        response_type=wallet_request_types.DIDGetInfoResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="did_find_lost_did",
        request_type=wallet_request_types.DIDFindLostDID,
        response_type=wallet_request_types.DIDFindLostDIDResponse,
    ),
    # NFT wallet
    WalletRpcMetadata(
        endpoint_name="nft_mint_nft",
        request_type=wallet_request_types.NFTMintNFTRequest,
        response_type=wallet_request_types.NFTMintNFTResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_count_nfts",
        request_type=wallet_request_types.NFTCountNFTs,
        response_type=wallet_request_types.NFTCountNFTsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_get_nfts",
        request_type=wallet_request_types.NFTGetNFTs,
        response_type=wallet_request_types.NFTGetNFTsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_get_by_did",
        request_type=wallet_request_types.NFTGetByDID,
        response_type=wallet_request_types.NFTGetByDIDResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_set_nft_did",
        request_type=wallet_request_types.NFTSetNFTDID,
        response_type=wallet_request_types.NFTSetNFTDIDResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_set_nft_status",
        request_type=wallet_request_types.NFTSetNFTStatus,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_get_wallet_did",
        request_type=wallet_request_types.NFTGetWalletDID,
        response_type=wallet_request_types.NFTGetWalletDIDResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_get_wallets_with_dids",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.NFTGetWalletsWithDIDsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_get_info",
        request_type=wallet_request_types.NFTGetInfo,
        response_type=wallet_request_types.NFTGetInfoResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_transfer_nft",
        request_type=wallet_request_types.NFTTransferNFT,
        response_type=wallet_request_types.NFTTransferNFTResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_add_uri",
        request_type=wallet_request_types.NFTAddURI,
        response_type=wallet_request_types.NFTAddURIResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_calculate_royalties",
        request_type=wallet_request_types.NFTCalculateRoyalties,
        response_type=wallet_request_types.NFTCalculateRoyaltiesResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_mint_bulk",
        request_type=wallet_request_types.NFTMintBulk,
        response_type=wallet_request_types.NFTMintBulkResponse,
        tx_endpoint=True,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_set_did_bulk",
        request_type=wallet_request_types.NFTSetDIDBulk,
        response_type=wallet_request_types.NFTSetDIDBulkResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="nft_transfer_bulk",
        request_type=wallet_request_types.NFTTransferBulk,
        response_type=wallet_request_types.NFTTransferBulkResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    # Remote wallet
    WalletRpcMetadata(
        endpoint_name="register_remote_coins",
        request_type=wallet_request_types.RegisterRemoteCoins,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="get_coin_records",
        request_type=wallet_request_types.GetCoinRecords,
        response_type=wallet_request_types.GetCoinRecordsResponse,
    ),
    # Pool wallet
    WalletRpcMetadata(
        endpoint_name="pw_join_pool",
        request_type=wallet_request_types.PWJoinPool,
        response_type=wallet_request_types.PWJoinPoolResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="pw_self_pool",
        request_type=wallet_request_types.PWSelfPool,
        response_type=wallet_request_types.PWSelfPoolResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="pw_absorb_rewards",
        request_type=wallet_request_types.PWAbsorbRewards,
        response_type=wallet_request_types.PWAbsorbRewardsResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="pw_status",
        request_type=wallet_request_types.PWStatus,
        response_type=wallet_request_types.PWStatusResponse,
    ),
    # Data layer wallet
    WalletRpcMetadata(
        endpoint_name="create_new_dl",
        request_type=wallet_request_types.CreateNewDL,
        response_type=wallet_request_types.CreateNewDLResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_track_new",
        request_type=wallet_request_types.DLTrackNew,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_stop_tracking",
        request_type=wallet_request_types.DLStopTracking,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_latest_singleton",
        request_type=wallet_request_types.DLLatestSingleton,
        response_type=wallet_request_types.DLLatestSingletonResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_singletons_by_root",
        request_type=wallet_request_types.DLSingletonsByRoot,
        response_type=wallet_request_types.DLSingletonsByRootResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_update_root",
        request_type=wallet_request_types.DLUpdateRoot,
        response_type=wallet_request_types.DLUpdateRootResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_update_multiple",
        request_type=wallet_request_types.DLUpdateMultiple,
        response_type=wallet_request_types.DLUpdateMultipleResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_history",
        request_type=wallet_request_types.DLHistory,
        response_type=wallet_request_types.DLHistoryResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_owned_singletons",
        request_type=wallet_request_types.Empty,
        response_type=wallet_request_types.DLOwnedSingletonsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_get_mirrors",
        request_type=wallet_request_types.DLGetMirrors,
        response_type=wallet_request_types.DLGetMirrorsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_new_mirror",
        request_type=wallet_request_types.DLNewMirror,
        response_type=wallet_request_types.DLNewMirrorResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_delete_mirror",
        request_type=wallet_request_types.DLDeleteMirror,
        response_type=wallet_request_types.DLDeleteMirrorResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="dl_verify_proof",
        request_type=DLProof,
        response_type=VerifyProofResponse,
    ),
    # Verified credentials
    WalletRpcMetadata(
        endpoint_name="vc_mint",
        request_type=wallet_request_types.VCMint,
        response_type=wallet_request_types.VCMintResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="vc_get",
        request_type=wallet_request_types.VCGet,
        response_type=wallet_request_types.VCGetResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="vc_get_list",
        request_type=wallet_request_types.VCGetList,
        response_type=wallet_request_types.VCGetListResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="vc_spend",
        request_type=wallet_request_types.VCSpend,
        response_type=wallet_request_types.VCSpendResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    WalletRpcMetadata(
        endpoint_name="vc_add_proofs",
        request_type=wallet_request_types.VCAddProofs,
        response_type=wallet_request_types.Empty,
    ),
    WalletRpcMetadata(
        endpoint_name="vc_get_proofs_for_root",
        request_type=wallet_request_types.VCGetProofsForRoot,
        response_type=wallet_request_types.VCGetProofsForRootResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="vc_revoke",
        request_type=wallet_request_types.VCRevoke,
        response_type=wallet_request_types.VCRevokeResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    # CR-CATs
    WalletRpcMetadata(
        endpoint_name="crcat_approve_pending",
        request_type=wallet_request_types.CRCATApprovePending,
        response_type=wallet_request_types.CRCATApprovePendingResponse,
        tx_endpoint=True,
        auto_push=True,
    ),
    # Signer protocol
    WalletRpcMetadata(
        endpoint_name="gather_signing_info",
        request_type=wallet_request_types.GatherSigningInfo,
        response_type=wallet_request_types.GatherSigningInfoResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="apply_signatures",
        request_type=wallet_request_types.ApplySignatures,
        response_type=wallet_request_types.ApplySignaturesResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="submit_transactions",
        request_type=wallet_request_types.SubmitTransactions,
        response_type=wallet_request_types.SubmitTransactionsResponse,
    ),
    WalletRpcMetadata(
        endpoint_name="execute_signing_instructions",
        request_type=wallet_request_types.ExecuteSigningInstructions,
        response_type=wallet_request_types.ExecuteSigningInstructionsResponse,
    ),
]
