import React from 'react';
import { Box, Typography } from '@material-ui/core';
import { Trans } from '@lingui/macro';
import type PlotNFT from '../../types/PlotNFT';
import useCurrencyCode from '../../hooks/useCurrencyCode';
import usePlotNFTDetails from '../../hooks/usePlotNFTDetails';
import { Flex, TooltipIcon } from '@chia/core';
import toBech32m from '../../util/toBech32m';

type Props = {
  nft: PlotNFT;
  variant?: string;
};

export default function PlotNFTName(props: Props) {
  const {
    variant,
    nft,
    nft: {
      pool_state: {
        p2_singleton_puzzle_hash,
      },
    },
  } = props;

  const currencyCode = useCurrencyCode();
  const { humanName } = usePlotNFTDetails(nft);
  const poolContractAddress = currencyCode 
    ? toBech32m(p2_singleton_puzzle_hash, currencyCode.toLowerCase())
    : '';

  return (
    <Flex gap={1} alignItems="center">
      <Typography variant={variant} noWrap>
        {humanName}
      </Typography>
      <TooltipIcon>
        <Flex flexDirection="column">
          <Box>
            <Trans>Autogenerated name from pool contract address</Trans>
          </Box>
          {poolContractAddress}
        </Flex>
      </TooltipIcon>
    </Flex>

  );
}

PlotNFTName.defaultProps = {
  variant: 'body1',
};
