import React from 'react';
import { Typography } from '@material-ui/core';
import { Trans } from '@lingui/macro';
import styled from 'styled-components';
import type PlotNFT from '../../types/PlotNFT';
import usePlotNFTDetails from '../../hooks/usePlotNFTDetails';
import { Address, Flex, TooltipIcon } from '@chia/core';

const StyledTitle = styled(Typography)`
  font-size: 0.75rem;
`;

type Props = {
  nft: PlotNFT;
  variant?: string;
};

export default function PlotNFTName(props: Props) {
  const {
    variant,
    nft,
    nft: {
      pool_state: {
        p2_singleton_puzzle_hash,
      },
    },
  } = props;

  const { humanName } = usePlotNFTDetails(nft);

  return (
    <Flex gap={1} alignItems="center">
      <Typography variant={variant} noWrap>
        {humanName}
      </Typography>
      <TooltipIcon interactive>
        <Flex flexDirection="column" gap={1}>
          <StyledTitle variant="body2" color="textSecondary">
            <Trans>Autogenerated name from pool contract address</Trans>
          </StyledTitle>
          <Address value={p2_singleton_puzzle_hash} copyToClipboard />
        </Flex>
      </TooltipIcon>
    </Flex>

  );
}

PlotNFTName.defaultProps = {
  variant: 'body1',
};
