name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set env
      run: |
        python3 -m venv env
        ln -s env/bin/activate
        . activate
    - name: Install dependencies
      env:
        CHIA_MACHINE_SSH_KEY: ${{ secrets.CHIA_MACHINE_SSH_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${CHIA_MACHINE_SSH_KEY}"
        python -m pip install --upgrade pip
        # this next nasty line install the first three things
        # in requirements.txt individually
        head -3 requirements.txt | xargs -L1 pip install
        pip install -r requirements.txt 
        pip install -e .
    - name: Test with pytest
      run: |
        pip install pytest
        py.test tests
