
enum OfferState {
  PENDING_ACCEPT = 'PENDING_ACCEPT',
  PENDING_CONFIRM = 'PENDING_CONFIRM',
  PENDING_CANCEL = 'PENDING_CANCEL',
  CANCELLED = 'CANCELLED',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
};

export default OfferState;
