name: Build and test MacOS Core

on: [push, pull_request]

jobs:
  build:
    name: Build and test MacOS Core
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
        os: [macOS-latest]

    steps:
    - name: Cancel previous runs on the same branch
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        # Note that new runners may break this https://github.com/actions/cache/issues/292
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Download Chia test blocks and plots
      run: |
        mkdir $HOME/.chia
        cd $HOME/.chia
        curl -L https://download.chia.net/tests/blocks-2020-12-17.tgz | tar -zx
        curl -L https://download.chia.net/tests/test-plots-2021-01-04.tgz | tar -zx

    - name: Run install script
      env:
        INSTALL_PYTHON_VERSION: ${{ matrix.python-version }}
        BUILD_VDF_CLIENT: "N"
      run: |
        brew install boost
        sh install.sh

    - name: Install timelord
      run: |
        . ./activate
        sh install-timelord.sh
        ./vdf_bench square_asm 400000

    - name: Install developer requirements
      run: |
        . ./activate
        venv/bin/python -m pip install -r requirements-dev.txt

    - name: Test blockchain code with pytest
      run: |
        . ./activate
        ./venv/bin/py.test tests/core -s -v --durations 0
