name: Build Windows

on: [push, pull_request]

jobs:
  build:
    name: Windows installer on 3.7
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
          # we need fetch-depth 0 so setuptools_scm can resolve tags

      - uses: actions/setup-python@v1
        name: Install Python 3.7
        with:
          python-version: "3.7"

      - name: Build Windows installer with build_scripts\build_windows.ps1
        run: |
          $env:path="C:\Program` Files` (x86)\Microsoft` Visual` Studio\2019\Enterprise\SDK\ScopeCppSDK\vc15\VC\bin\;$env:path"
          .\build_scripts\build_windows.ps1

      - name: Upload Windows exe's to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows-Exe
          path: ${{ github.workspace }}\electron-react\Chia-win32-x64\

      - name: Upload Installer to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Windows-Installers
          path: ${{ github.workspace }}\electron-react\release-builds\
