#
# THIS FILE IS GENERATED. SEE https://github.com/Chia-Network/chia-blockchain/tree/main/tests#readme
#
name: MacOS blockchain Tests

on:
  push:
    branches:
      - main
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    name: MacOS blockchain Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10']
        os: [macOS-latest]
    env:
      CHIA_ROOT: ${{ github.workspace }}/.chia/mainnet
      JOB_FILE_NAME: tests_${{ matrix.os }}_python-${{ matrix.python-version }}_blockchain

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create keychain for CI use
      run: |
        security create-keychain -p foo chiachain
        security default-keychain -s chiachain
        security unlock-keychain -p foo chiachain
        security set-keychain-settings -t 7200 -u chiachain

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip
      uses: actions/cache@v3
      with:
        # Note that new runners may break this https://github.com/actions/cache/issues/292
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache test blocks and plots
      uses: actions/cache@v2
      id: test-blocks-plots
      with:
        path: |
          ${{ github.workspace }}/.chia/blocks
          ${{ github.workspace }}/.chia/test-plots
        key: 0.29.0

    - name: Checkout test blocks and plots
      if: steps.test-blocks-plots.outputs.cache-hit != 'true'
      run: |
        wget -qO- https://github.com/Chia-Network/test-cache/archive/refs/tags/0.29.0.tar.gz | tar xzf -
        mkdir ${{ github.workspace }}/.chia
        mv ${{ github.workspace }}/test-cache-0.29.0/* ${{ github.workspace }}/.chia

    - name: Run install script
      env:
        INSTALL_PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        brew install boost
        sh install.sh -d

# Omitted installing Timelord

    - name: Test blockchain code with pytest
      run: |
        . ./activate
        venv/bin/coverage run --rcfile=.coveragerc --module pytest --durations=10  -n 4 -m "not benchmark" tests/blockchain/test_blockchain.py tests/blockchain/test_blockchain_transactions.py

    - name: Process coverage data
      run: |
        venv/bin/coverage combine --rcfile=.coveragerc .coverage.*
        venv/bin/coverage xml --rcfile=.coveragerc -o coverage.xml
        mkdir coverage_reports
        cp .coverage "coverage_reports/.coverage.${{ env.JOB_FILE_NAME }}"
        cp coverage.xml "coverage_reports/coverage.${{ env.JOB_FILE_NAME }}.xml"
        venv/bin/coverage report --rcfile=.coveragerc --show-missing

    - name: Publish coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage_reports/*
        if-no-files-found: error
#
# THIS FILE IS GENERATED. SEE https://github.com/Chia-Network/chia-blockchain/tree/main/tests#readme
#
