name: 🩹 Conflict Check
on:
  # So that PRs touching the same files as the push are updated
  push:
    branches-ignore:
      - "tmp/**"
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are behind main
        uses: Chia-Network/actions/label-conflict@main
        with:
          labelToAddOnConflict: "merge_conflict"
          secretToken: "${{ secrets.GITHUB_TOKEN }}"
          # targeting 2 minutes of retry, longest observed window thus far is ~30 seconds
          retryIntervalSec: 5
          retryMax: 24
