name: library

on:
  workflow_call:
    outputs:
      library:
        description: "The library in JSON form."
        value: ${{ jobs.library.outputs.library }}

jobs:
  library:
    name: Set library output
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: chia-network/actions/setup-python@main
        with:
          python-version: '3.9'

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Generate library output
        id: library
        run: |
          python .github/workflows/library.py > library.json
          cat library.json
          echo ::set-output name=library::$(cat library.json)

    outputs:
      library: ${{ steps.library.outputs.library }}
