# Starts a sync test for every new release (pre-releases included)
name: Start Sync Test

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  start_release:
    name: Starts Sync Test
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        uses: Chia-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: Chia-Network/actions/github/jwt@main

      - name: Trigger Workflow
        run: |
          curl -s -XPOST -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" --data '{"test_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/sync-test/$RELEASE_TAG/start
          curl -s -XPOST -H "Authorization: Bearer ${{ env.JWT_TOKEN }}" --data '{"test_ref": "${{ env.RELEASE_TAG }}"}' ${{ secrets.GLUE_API_URL }}/api/v1/sync-test/$RELEASE_TAG/success/deploy
